import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox"] });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
const p = await ctx.newPage();
await p.goto("http://localhost:4173", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(700);
await p.locator("button:has-text('Sign in')").first().click();
await p.waitForTimeout(500);
await p.locator("button:has-text('Fill demo')").first().click();
await p.locator("button[type=submit]").first().click();
await p.waitForTimeout(1500);
const selectNav = p.locator("select").first();
console.log("MOBILE_NAV_SELECT=", (await selectNav.count()) > 0 ? "present" : "missing");
await p.screenshot({ path: "/tmp/rbps_e2e/mobile-command.png" });
await selectNav.selectOption("workspace");
await p.waitForTimeout(1800);
console.log("MOBILE_WS=", (await p.locator("text=Planning Workspace").count()) > 0 ? "ok" : "fail");
await p.screenshot({ path: "/tmp/rbps_e2e/mobile-workspace.png" });
await b.close();
console.log("MOBILE_OK");
